package work;

public class test {
	Lion ll=new Lion(5,5);
	Wolf ww=new Wolf(1, 1);
	Rabbit rr=new Rabbit(2,2);
	void d(String s1)
	{
		if(s1.charAt(0)=='L')
		{
			if(ll.x<10)
			{
			ll.x=ll.x+1;
			System.out.println("狮子坐标:"+ll.x+","+ll.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='W')
		{
			if(ww.x<10)
			{
			ww.x=ww.x+1;
			System.out.println("狼坐标:"+ww.x+","+ww.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='R')
		{
			if(rr.x<10)
			{
			rr.x=rr.x+1;
			System.out.println("兔子坐标:"+rr.x+","+rr.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		
	}
	void x(String s1)
	{
		if(s1.charAt(0)=='L')
		{
			if(ll.x>0)
			{
			ll.x=ll.x-1;
			System.out.println("狮子坐标:"+ll.x+","+ll.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='W')
		{
			if(ww.x>0)
			{
			ww.x=ww.x-1;
			System.out.println("狼坐标:"+ww.x+","+ww.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='R')
		{
			if(rr.x>0)
			{
			rr.x=rr.x-1;
			System.out.println("兔子坐标:"+rr.x+","+rr.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
	}
	void n(String s1)
	{
		if(s1.charAt(0)=='L')
		{
			if(ll.y>0)
			{
			ll.y=ll.y-1;
			System.out.println("狮子坐标:"+ll.x+","+ll.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='W')
		{
			if(ww.y>0)
			{
			ww.y=ww.y-1;
			System.out.println("狼坐标:"+ww.x+","+ww.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='R')
		{
			if(rr.y>0)
			{
			rr.y=rr.y-1;
			System.out.println("兔子坐标:"+rr.x+","+rr.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		
	}
	void b(String s1)
	{
		if(s1.charAt(0)=='L')
		{
			if(ll.y<10)
			{
			ll.y=ll.y+1;
			System.out.println("狮子坐标:"+ll.x+","+ll.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='W')
		{
			if(ww.y<10)
			{
			ww.y=ww.y+1;
			if(ww.y!=-1||ww.x!=-1)		
			System.out.println("狼坐标:"+ww.x+","+ww.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
		if(s1.charAt(0)=='R')
		{
			if(rr.y<10)
			{
			rr.y=rr.y+1;
			if(rr.y!=-1||rr.x!=-1)
			System.out.println("兔子坐标:"+rr.x+","+rr.y);
			}
			else
			{
				System.out.println("错了");
			}
		}
	}
	void ci()
	{
		if(ll.x==ww.x&&ll.y==ww.y)
		{
			ww.x=-1;
			ww.y=-1;
			System.out.println("狼没了");
		}
		if(rr.x==ww.x&&rr.y==ww.y)
		{
			rr.x=-1;
			rr.y=-1;
			System.out.println("兔没了");
		}
		if(ll.x==rr.x&&ll.y==rr.y)
		{
			rr.x=-1;
			rr.y=-1;
			System.out.println("兔没了");
		}
	}
	
}
